#' fetchClustalOmega
#'
#' \code{<function>} Return a seqinr aligment containing sequences that are
#' aligned by the ClustalOmega alignment algorithm. The user may search the
#' referenceDB for a set of BaliBASE sequences by entering the alignment ID
#' as input, or they may input a .mfa file containing the sequences in
#' fasta format.
#'
#' @param inputSeqs The sequences the user would like to align. Can either
#' be an alignment ID of a BaliBASE alignment or a file path to a .mfa file
#' containing sequences for an alignment.
#'
#' @param readType The type of characters found in the provided input
#' sequences. Can either be "AA", "DNA" or "RNA" depending on the characters
#' in the file.
#'
#' For the remaining parameters:
#' Please view details on \code{msa::msa()} function which provides details
#' about the remaining parameters for writeClustalOmega
#'
#' @return The alignment generated by ClustalOmega in the form of a seqinr
#' alignment.
#'
#' @export
#' @import msa

fetchClustalOmega <- function(inputSeqs, readType = c("AA", "DNA", "RNA"),
                        cluster = "default", gapOpening = "default",
                        gapExtension = "default", maxiters = "default",
                        substitutionMatrix = "default", type = "default",
                        order = c("aligned", "input"), verbose = FALSE,
                        help = FALSE, ...) {
  aln <- referenceDB$alignments[[inputSeqs]]

  if (xor(is.null(aln), !file.exists(inputSeqs))) {
    # If the user provided a valid filepath, convert the
    # fasta file into a XStringSet
    if (file.exists(inputSeqs)) {
      seq <- convertXStringSet(inputSeqs, readType)
    }

    # If the user provided a valid alnID, create a
    # temporary directory that will contain the alignment from
    # the database. Then convert the mfa into an XStringSet
    else if (!is.null(aln)) {
      writeAln(inputSeqs, fileName = "out", directory = "data/temp")
      seq <- convertXStringSet(paste("data/temp", "/", "out.mfa", sep = ""), readType)
      file.remove(paste("data/temp", "/", "out.mfa", sep = ""))
    }
  }

  # If the inputSeqs the user provided is invalid
  else {
    stop("The InputSeqs you provided is invalid.\n
         If you are providing an alignment ID, make sure it
         exists in BaliBASE. If you are providing a file,
         make sure the filepath is correct. \n")
  }

  # Use msa library to create a ClustalOmega alignment
  alignment <- msa::msaClustalOmega(seq, cluster, gapOpening, gapExtension,
                              maxiters, substitutionMatrix, type, order,
                              verbose, help, ...)

  # Convert the alignment into seqinr alignment and write is as a msf file
  seqinrAln <- msa::msaConvert(alignment, type = "seqinr::alignment")

  return (seqinrAln)
}











